---
title: "analysis"
author: "Tejas"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(lattice); library(ggplot2); library(caret); library(randomForest); library(rpart); library(rpart.plot);
```

Two models are chosen:
1) Classification Tree
2) Random Forest
The model with the highest accuracy will be chosen for the final prediction.
```{r}
trainset <- read.csv("C:/Users/Tejas Ravishankar/Desktop/pml-training.csv", na.strings=c("NA","#DIV/0!", ""))
testset <- read.csv("C:/Users/Tejas Ravishankar/Desktop/pml-testing.csv", na.strings=c("NA","#DIV/0!", ""))
trainset<-trainset[,colSums(is.na(trainset)) == 0]
testset <-testset[,colSums(is.na(testset)) == 0]
trainset   <-trainset[,-c(1:7)]
testset <-testset[,-c(1:7)]

plot(trainset$classe, col="blue", main="Plot of levels of variable classe within the Training data set", xlab="classe", ylab="Frequency")
```
```{r}
m1 <- rpart(classe ~ ., data=trainset, method="class")

p1 <- predict(m1, testset, type = "class")

# Plot the Decision Tree
rpart.plot(m1, main="Classification Tree", extra=102, under=TRUE, faclen=0)
```
```{r}
m2 <- randomForest(classe ~. , data=trainset, method="class")

# Predicting:
p2 <- predict(m2, testset, type = "class")

```

```{r}
finalpred <- predict(m2, testset, type="class")
finalpred
```
